### ISSUE TITLE
Removing from the DOM

### ISSUE THREAD

**Issue by ianserlin** [cwohlman/meteor-materialize-modal#1]
You'll need to add a way to remove the Blaze inserted dom elements. The materialize modal does not do that automatically for you. In HarvestWindow I added a `close` method with a handle to the Blaze returned `View` that knows how to remove from the dom.

**Comment by cwohlman** [comment]
So this line doesn't do the trick: https://github.com/cwohlman/meteor-materialize-modal/blob/master/cwohlman:materialize-modal.js#L17?

**Comment by ianserlin** [comment]
ahh missed it
