### ISSUE TITLE
openModal is not a function

### ISSUE THREAD

**Issue by Narven** [cwohlman/meteor-materialize-modal#2]
I get this when i call the modal

```
Error: Exception in setTimeout callback:
TypeError: $(...).openModal is not a function
    at cwohlman_materialize-modal.js:43
```

**Comment by cwohlman** [comment]
Oops. Looks like we're only using this package internally and it has dependencies on materialize's js. You could try forking this package to work with bootstrap or bootbox or you could download materialize into your project: http://materializecss.com/getting-started.html
